#!/bin/bash
# Show files with average latencies greater than a threshold

if [ $# -ne 1 ]; then
	>&2 echo -e "Pass a threshold value."
	exit 1
fi

find loot -name 'ping_monitor*' -print0 -printf " " -type f -exec sed -n '$p;' {} \; | awk '{print $1" "$7}' | sed -r 's|^(.*) [0-9.]+/[0-9.]+/([0-9.])|\1 \2|g' | awk -v val=$1 '$2 > val' | sort -n