#!/bin/bash
# Show the maximum latency found within the data collected

find loot -name 'ping_monitor*' -type f -exec sed -n '$p;' {} \; | awk '{print $6}' | awk -F'/' '{print $3}' | sort -n | tail -n1